service: serverless-todos-yt
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: arn:aws:dynamodb:us-east-2:732094371799:table/TodoTable

functions:
  addTodo:
    handler: src/functions/addTodo.handler
    events:
      - httpApi:
          path: /
          method: post
  fetchTodos:
    handler: src/functions/fetchTodos.handler
    events:
      - httpApi:
          path: /
          method: get
  fetchTodo:
    handler: src/functions/fetchTodo.handler
    events:
      - httpApi:
          path: /todo/{id}
          method: get
  updateTodo:
    handler: src/functions/updateTodo.handler
    events:
      - httpApi:
          path: /todo/{id}
          method: put

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        